### ISSUE TITLE
Discussion

### ISSUE THREAD

**Issue by evoactivity** [evoactivity/the-tooling-pit-of-incoherence#1]
Feedback, thoughts, ideas, opinions can be left here.

**Comment by locks** [comment]
Thanks for writing this! It's great to have someone energized to pick this initiative back up 😁 We definitely need a lot of polish in this area.

I was thinking, could you actually enable Discussions on this repository so the discussions can be focused on each topic?
I've left below a couple shorter answers.

### Does anyone use `ember-cli-remote-inspector`?
Archived!

### Is the `ember-tooling/prettier-vscode` repo still needed?
Archived!

### Can we verify the vscode account like vue has, so the ember tooling extensions get a blue badge?
Ember Tooling is not yet a core project, so some work is in order 😁

### We should spruce up the ember-tooling organisation. Add some logos and nicely formatted readme's.
Yes, please!

### VS Code extensions should be consistently named eg
> `lifeart.vscode-ember-unstable` -> `emberjs.vscode-ember-language-server`
> `lifeart.vscode-glimmer-syntax` -> `emberjs.vscode-ember-syntax-highlighting`

I'm under the impression that the marketplace is quite limited and this might be tricky, but if you can get the relevant parties to agree it might be might. Note that it'd be `ember-tooling.<extension name>`.

### Publish vscode extensions to [Open VSX Registry](https://open-vsx.org/)
Let's do it! I've pinged you regarding account creating, and you already have a PR pending.

### Need to write contributing guides covering
Send them in!

**Comment by evoactivity** [comment]
Sweet. I've opened the discussions, forgot that was a thing 😅

I'll cloe this issue and discussion can continue in the appropriate tab.
